### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by normaliok** [qeeqbox/url-sandbox#3]
I get error 500 both when trying to login to 127.0.0.1:8000 or trying to register

**Comment by giga-a** [comment]
Hey @normaliok
That issue was caused by pymongo driver and I just fixed it
Let me know if that fix works for you or not

**Comment by normaliok** [comment]
What exactly I need to do to check if it's fixed?

**Comment by giga-a** [comment]
@normaliok re-download and install it, it should work, if not let me know

**Comment by normaliok** [comment]
It's fine now!
